services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     - DATABASE_URL=postgresql://postgres:postgres@db:5432/capability_lens
  #     - NODE_ENV=production
  #     - NEXTAUTH_URL=http://localhost:3000
  #     - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #   healthcheck:
  #     test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3

  db:
    image: postgres:17.2
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=capability_lens
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db:
    driver: local
